"""update transport table

Revision ID: 09a9e6e0fec7
Revises: a9b176598c4b
Create Date: 2025-05-10 21:41:59.196314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a9e6e0fec7'
down_revision: Union[str, None] = 'a9b176598c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transport_pass', sa.Column('balance', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'transport_pass', 'users', ['username'], ['username'])
    op.drop_column('transport_pass', 'saldo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transport_pass', sa.Column('saldo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transport_pass', type_='foreignkey')
    op.drop_column('transport_pass', 'balance')
    # ### end Alembic commands ###
